openapi: 3.0.0
info:
  title: Movies & Users API
  version: 1.0.0
  description: REST API для керування користувачами та фільмами
  contact:
    name: API Support
    email: team@example.com
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /api/v1/movies:
    get:
      summary: Отримати список фільмів
      responses:
        '200':
          description: Список фільмів
    post:
      summary: Додати новий фільм
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - year
              properties:
                title:
                  type: string
                year:
                  type: integer
      responses:
        '201':
          description: Фільм додано
  /api/v1/movies/{id}:
    get:
      summary: Отримати фільм за ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Дані про фільм
        '404':
          description: Фільм не знайдено
  /api/v1/users:
    get:
      summary: Отримати список усіх користувачів
      responses:
        '200':
          description: Список користувачів
    post:
      summary: Створити нового користувача
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - role
                - nickname
                - password
                - email
              properties:
                username:
                  type: string
                role:
                  type: string
                nickname:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Користувача створено
  /api/v1/users/{param}:
    get:
      summary: Отримати користувача за ID або username
      parameters:
        - name: param
          in: path
          required: true
          schema:
            type: string
          description: ID (число) або username (рядок)
      responses:
        '200':
          description: Інформація про користувача
        '404':
          description: Користувача не знайдено
    put:
      summary: Оновити дані користувача за ID або username
      parameters:
        - name: param
          in: path
          required: true
          schema:
            type: string
          description: ID (число) або username (рядок)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                role:
                  type: string
                nickname:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: Користувача оновлено
        '404':
          description: Користувача не знайдено
    delete:
      summary: Видалити користувача за ID або username
      parameters:
        - name: param
          in: path
          required: true
          schema:
            type: string
          description: ID (число) або username (рядок)
      responses:
        '200':
          description: Користувача видалено
        '404':
          description: Користувача не знайдено
components: {}
tags: []
